# Use root/example as user/password credentials
version: '3.1'

services:
  mongodb:
    image: mongo
    volumes:
      - ./mongodb:/data/db:cached
    ports:
      - 27017:27017
  client:
    build: ./client
    restart: always
    container_name: app-client
    depends_on:
      - server
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app:cached
  server:
    build: ./server
    restart: always
    container_name: app-server
    ports:
      - '4000:4000'
    environment:
      MONGO_URL: mongodb
      PORT: 4000
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ./server:/app:cached
