# Use root/example as user/password credentials
version: '3.1'

services:
  client:
    build: ./client
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client:/app
