# Use root/example as user/password credentials
version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./mongodb:/data/db:cached
    ports:
      - 27017:27017
  client:
    build: ./client
    restart: always
    container_name: client
    depends_on:
      - server
    env_file:
      - .env.development
    ports:
      - '80:80'
    volumes:
      - ./client:/app:cached
  server:
    build: ./server
    restart: always
    container_name: server
    ports:
      - '4000:4000'
    env_file:
      - .env.development
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ./server:/app:cached
  auth:
    build: auth
    restart: always
    container_name: auth
    ports:
      - '4100:4100'
    env_file:
      - .env.development
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ./auth:/app:cached
  email:
    build: ./email
    restart: always
    container_name: email
    ports:
      - '4200:4200'
    env_file:
      - .env.development
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ./email:/app:cached
