# Use root/example as user/password credentials
version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./mongodb:/data/db:cached
    ports:
      - 27017:27017
  client:
    build: ./client
    restart: always
    container_name: app-client
    depends_on:
      - server
    environment:
      - REACT_APP_API_URI=http://localhost:4000/api/
      - REACT_APP_AUTH_URI=http://localhost:4100/api/
    ports:
      - '80:80'
    volumes:
      - ./client:/app:cached
  server:
    build: ./server
    restart: always
    container_name: server
    ports:
      - '4000:4000'
    environment:
      MONGO_URL: mongodb
      PORT: 4000
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ./server:/app:cached
  auth:
    build: ./auth
    restart: always
    container_name: auth
    ports:
      - '4100:4100'
    environment:
      MONGO_URL: mongodb
      PORT: 4100
      EMAIL_URL: http://email:4200/api/
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ./auth:/app:cached
  email:
    build: ./email
    restart: always
    container_name: email
    ports:
      - '4200:4200'
    environment:
      MONGO_URL: mongodb
      PORT: 4200
      FRONT_URL: http://localhost:80/set-new-password/
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ./email:/app:cached
